type: other8001
server:
  port: 8000
  ssl:
    key-store: E:/ssl/6123897_hzmzsx.xyz.pfx
    key-store-password: v0285kKl
    key-store-type: PKCS12
    enabled: true
  compression:
    enabled: true #开启压缩
    min-response-size: 2048
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  application:
    name: cloud-pay-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HZM0808/springCloud_Config.git
          search-paths:
           - springCloud_Config
      label: master

eureka:
  instance:
    instance-id: config8000 #${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    #ip-address: hzmzsx.xyz #这个修改会覆盖prefer-ip-address默认的ip，前提生效要prefer-ip-address为true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://hzmzsx.xyz:7001/eureka,https://hzmzsx.xyz:7002/eureka
